name: Java Maven CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin" # Opciones: temurin, zulu, adopt, etc.

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Set up environment variables
      - name: Load environment variables
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            cp .env.test .env
          else
            cp .env .env
          fi

      # Step 5: Run Maven tests
      - name: Build and Test
        run: mvn clean test
